#!/bin/bash

# Hyprland default configuration script
# Author: Generated by ChatGPT
# Purpose: Setup default Hyprland configuration

CONFIG_DIR="$HOME/.config/hypr"
CONFIG_FILE="$CONFIG_DIR/hyprland.conf"

# Create config directory if it doesn't exist
if [ ! -d "$CONFIG_DIR" ]; then
    mkdir -p "$CONFIG_DIR"
    echo "Created directory: $CONFIG_DIR"
fi

# Write default Hyprland configuration
cat > "$CONFIG_FILE" << 'EOF'
# ========================
# Hyprland Default Config
# ========================

# General
general {
    monitor=auto
    dpi=96
    vsync=full
}

# Input
input {
    kb_layout=us
    kb_repeatrate=25
    kb_repeatdelay=600
}

# Window Rules
windowrule {
    float=title: "FloatingApp"
}

# Bindings
bind {
    super+Return, exec, alacritty
    super+d, exec, rofi -show drun
    super+q, killactive
    super+Left, movewindow left 10
    super+Right, movewindow right 10
}

# Gaps & Borders
general {
    window_gap=10
    border_size=2
    border_color=0xFFAAAAAA
}

# Wallpaper (default)
monitor=*
    wallpaper=~/Pictures/wallpaper.jpg
    scaling=fill
EOF

echo "Default Hyprland configuration written to $CONFIG_FILE"
echo "You can now start Hyprland with: Hyprland"

